[package]
name = "backup_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpassword = "7.2.0"
copy_dir = "0.1.2"
sevenz-rust = {version = "0.6.1", features=["compress", "aes256"]}
